import { createContext, useContext, useEffect, useState, type ReactNode } from 'react';

export type Language = 'id' | 'en' | 'zh';
export type Theme = 'light' | 'dark';

const translations: Record<Language, Record<string, string>> = {
  id: {},
  en: {
    Beranda: 'Home', Pasar: 'Markets', Posisi: 'Positions', Mitra: 'Partners', Profil: 'Profile',
    Withdraw: 'Withdraw', Deposit: 'Deposit', 'Riwayat Pembayaran': 'Payment History',
    'Trade Sekarang': 'Trade now', 'Belum ada posisi terbuka.': 'No open positions.',
    'Belum ada riwayat transaksi.': 'No transaction history.', 'Ganti Akun': 'Switch account',
    'Saldo Utama': 'Main balance', 'Saldo Profit': 'Profit balance', 'Saldo Deposit': 'Deposit balance',
    'Kalender Ekonomi': 'Economic Calendar', 'Sinyal Trading': 'Trading Signals',
    'Layanan Pelanggan': 'Customer Service', 'Bahasa': 'Language', 'Pengaturan': 'Settings',
    'Pusat Klien': 'Client Center', 'Informasi Anda': 'Your Information',
    'Bank Penarikan': 'Withdrawal Bank', 'Ganti Password': 'Change Password',
    'Nama pemilik rekening': 'Account holder name', 'Nomor rekening': 'Account number',
    'Bank rekening': 'Bank name', 'Rekening Tujuan': 'Receiving Account',
    'Nama rekening:': 'Account name:', 'Nomor rekening:': 'Account number:',
    'Minimal deposit $200': 'Minimum deposit $200', 'Deposit Sekarang': 'Deposit now',
    'Pilih Metode Pembayaran': 'Select payment method', 'Pilih bank': 'Choose a bank',
    'Unggah foto / tangkapan layar bukti transfer': 'Upload a transfer receipt or screenshot',
    'Bukti transfer': 'Transfer receipt', 'Pratinjau demo: deposit tidak memindahkan dana sungguhan.': 'Demo preview: deposits do not move real money.',
    'Masuk dengan akun demo pengguna sebelum mengirim permintaan deposit.': 'Sign in with a demo user account before submitting a deposit request.',
    'Bukti transfer terkirim. Deposit Anda menunggu persetujuan admin.': 'Receipt submitted. Your deposit is waiting for admin approval.',
    'Belum ada rekening bank penarikan.': 'No withdrawal bank account saved.',
    'Tambah Rekening Bank': 'Add bank account', 'Pilih rekening': 'Select an account',
    'Jumlah penarikan': 'Withdrawal amount', 'Jumlah deposit': 'Deposit amount',
    'Tutup': 'Close', 'Simpan': 'Save', 'Batal': 'Cancel', 'Keluar': 'Log out',
    'Lanjutkan real': 'Continue verification', 'Promo': 'Promotions',
    'Tidak ada sinyal.': 'No signals.', 'Aktual: — · Prakiraan: — · Sebelumnya: —': 'Actual: — · Forecast: — · Previous: —',
    'Data contoh kalender ekonomi': 'Sample economic calendar data',
    'Rekening tujuan untuk metode ini belum diatur oleh admin.': 'No receiving account is configured for this method.',
    'Pratinjau demo, bukan transaksi nyata.': 'Demo preview, not a real transaction.',
    'Hubungi Layanan Pelanggan': 'Contact Customer Service', 'Jika Anda membutuhkan dukungan, hubungi kami melalui:': 'If you need support, contact us through:',
    'Nomor Telepon': 'Phone Number', Whatsapp: 'WhatsApp', Email: 'Email', 'Ngobrol dengan Agen kami': 'Chat with an agent',
    'Status Pembayaran': 'Payment Status', 'Tanggal Permintaan': 'Request Date', Terapkan: 'Apply',
    Semua: 'All', Menunggu: 'Pending', Disetujui: 'Approved', Gagal: 'Failed', Setoran: 'Deposits', Penarikan: 'Withdrawals',
    'Dari tanggal': 'From date', 'Sampai tanggal': 'To date', 'Tidak ada rekening bank penarikan.': 'No withdrawal bank account saved.',
    'Nama sesuai rekening': 'Name as shown on account', 'Nomor rekening pengirim': 'Sender account number',
    'Nama bank pengirim': 'Sender bank name', 'JPG atau PNG, maks 10 MB': 'JPG or PNG, up to 10 MB',
    'Minimal deposit': 'Minimum deposit',
    'Kembali ke Beranda': 'Back to Home', 'Bank Tujuan': 'Destination Bank', 'Nomor Rekening': 'Account Number',
    'Jumlah Penarikan (USD)': 'Withdrawal Amount (USD)', 'Tarik Dana': 'Request Withdrawal',
    'Pratinjau saja; tidak ada dana sungguhan yang dipindahkan.': 'Preview only; no real funds are moved.',
    'Penarikan belum terhubung ke layanan akun. Tidak ada dana yang dipindahkan.': 'Withdrawals are not connected to an account service. No funds were moved.',
    'Deposit payment': 'Deposit',
    'Transfer Bank BCA': 'Bank Transfer BCA', 'Transfer Bank BNI': 'Bank Transfer BNI',
    'Transfer Bank Mandiri': 'Bank Transfer Mandiri', 'Transfer Bank BRI': 'Bank Transfer BRI',
    'Transfer Bank BSI': 'Bank Transfer BSI', 'Transfer Bank CIMB': 'Bank Transfer CIMB',
    'Transfer Bank Permata': 'Bank Transfer Permata',
    'Ganti Kata Sandi': 'Change Password', Dokumen: 'Documents', 'Klik untuk menyalin UID': 'Copy UID',
    'Aktual · Prakiraan · Sebelumnya': 'Actual · Forecast · Previous', 'Aktual:': 'Actual:',
    'Prakiraan:': 'Forecast:', 'Sebelumnya:': 'Previous:', 'Peristiwa lainnya ›': 'More events ›',
    'Belum ada agenda.': 'No events scheduled.', Tinggi: 'High', Sedang: 'Medium', Rendah: 'Low',
    Hubungi: 'Contact', Telepon: 'Call', 'Tautan belum tersedia': 'Link is not available',
    'Ketik nama bank tujuan': 'Enter the destination bank', 'Nomor rekening tujuan': 'Destination account number',
    'File harus berupa gambar.': 'The file must be an image.', 'Ukuran gambar maksimal 10 MB.': 'The image must be 10 MB or smaller.',
    'Gambar tidak dapat dibaca.': 'The image could not be read.', 'Pratinjau bukti transfer': 'Transfer receipt preview',
    'Unggah bukti transfer': 'Upload transfer receipt', 'Ganti / hapus gambar': 'Replace / remove image',
    'Pilih pasar dan lakukan trading pertama Anda.': 'Choose a market to get started.',
    'Layanan mitra belum terhubung.': 'Partner services are not connected.',
    'Navigasi utama': 'Main navigation', 'Informasi': 'Information', Notifikasi: 'Notifications',
    'Belum ada notifikasi.': 'No notifications.', Bantuan: 'Help',
    'Pusat Bantuan': 'Help Center', 'Untuk pertanyaan umum, buka menu FAQ. Layanan bantuan pelanggan belum terhubung.': 'For common questions, open FAQ. Customer support is not connected.',
    FAQ: 'FAQ',
  },
  zh: {
    Beranda: '首页', Pasar: '市场', Posisi: '持仓', Mitra: '合作伙伴', Profil: '个人资料',
    Withdraw: '提现', Deposit: '存款', 'Riwayat Pembayaran': '付款记录',
    'Trade Sekarang': '立即交易', 'Belum ada posisi terbuka.': '暂无未平仓头寸。',
    'Belum ada riwayat transaksi.': '暂无交易记录。', 'Ganti Akun': '切换账户',
    'Saldo Utama': '主余额', 'Saldo Profit': '利润余额', 'Saldo Deposit': '存款余额',
    'Kalender Ekonomi': '经济日历', 'Sinyal Trading': '交易信号',
    'Layanan Pelanggan': '客户服务', Bahasa: '语言', Pengaturan: '设置',
    'Pusat Klien': '客户中心', 'Informasi Anda': '您的信息',
    'Bank Penarikan': '提现银行', 'Ganti Password': '更改密码',
    'Nama pemilik rekening': '账户持有人姓名', 'Nomor rekening': '账号',
    'Bank rekening': '银行名称', 'Rekening Tujuan': '收款账户',
    'Nama rekening:': '账户名称：', 'Nomor rekening:': '账号：',
    'Minimal deposit $200': '最低存款 $200', 'Deposit Sekarang': '立即存款',
    'Pilih Metode Pembayaran': '选择付款方式', 'Pilih bank': '选择银行',
    'Unggah foto / tangkapan layar bukti transfer': '上传转账凭证或截图',
    'Bukti transfer': '转账凭证', 'Pratinjau demo: deposit tidak memindahkan dana sungguhan.': '演示预览：存款不会转移真实资金。',
    'Masuk dengan akun demo pengguna sebelum mengirim permintaan deposit.': '请先使用演示用户账户登录，再提交存款申请。',
    'Bukti transfer terkirim. Deposit Anda menunggu persetujuan admin.': '凭证已提交，存款等待管理员批准。',
    'Belum ada rekening bank penarikan.': '尚未保存提现银行账户。',
    'Tambah Rekening Bank': '添加银行账户', 'Pilih rekening': '选择账户',
    'Jumlah penarikan': '提现金额', 'Jumlah deposit': '存款金额',
    Tutup: '关闭', Simpan: '保存', Batal: '取消', Keluar: '退出',
    Promo: '优惠活动', 'Tidak ada sinyal.': '暂无信号。',
    'Aktual: — · Prakiraan: — · Sebelumnya: —': '实际：— · 预测：— · 前值：—',
    'Data contoh kalender ekonomi': '经济日历示例数据',
    'Rekening tujuan untuk metode ini belum diatur oleh admin.': '管理员尚未为此方式配置收款账户。',
    'Pratinjau demo, bukan transaksi nyata.': '演示预览，不是真实交易。',
    'Hubungi Layanan Pelanggan': '联系客户服务', 'Jika Anda membutuhkan dukungan, hubungi kami melalui:': '如需帮助，请通过以下方式联系我们：',
    'Nomor Telepon': '电话号码', Whatsapp: 'WhatsApp', Email: '电子邮件', 'Ngobrol dengan Agen kami': '与客服交谈',
    'Status Pembayaran': '付款状态', 'Tanggal Permintaan': '申请日期', Terapkan: '应用',
    Semua: '全部', Menunggu: '待处理', Disetujui: '已批准', Gagal: '失败', Setoran: '存款', Penarikan: '提现',
    'Dari tanggal': '开始日期', 'Sampai tanggal': '结束日期', 'Nama sesuai rekening': '与账户一致的姓名',
    'Nomor rekening pengirim': '付款人账号', 'Nama bank pengirim': '付款人银行名称',
    'JPG atau PNG, maks 10 MB': 'JPG 或 PNG，最大 10 MB', 'Kembali ke Beranda': '返回首页',
    'Bank Tujuan': '收款银行', 'Nomor Rekening': '账号', 'Jumlah Penarikan (USD)': '提现金额（美元）',
    'Tarik Dana': '提交提现申请', 'Pratinjau saja; tidak ada dana sungguhan yang dipindahkan.': '仅为预览；不会转移真实资金。',
    'Penarikan belum terhubung ke layanan akun. Tidak ada dana yang dipindahkan.': '提现尚未连接到账户服务。未转移任何资金。',
    'Deposit payment': '存款', 'Transfer Bank BCA': 'BCA 银行转账', 'Transfer Bank BNI': 'BNI 银行转账',
    'Transfer Bank Mandiri': 'Mandiri 银行转账', 'Transfer Bank BRI': 'BRI 银行转账',
    'Transfer Bank BSI': 'BSI 银行转账', 'Transfer Bank CIMB': 'CIMB 银行转账', 'Transfer Bank Permata': 'Permata 银行转账',
    'Ganti Kata Sandi': '更改密码', Dokumen: '文件',
    'Aktual · Prakiraan · Sebelumnya': '实际 · 预测 · 前值', 'Aktual:': '实际：',
    'Prakiraan:': '预测：', 'Sebelumnya:': '前值：', 'Peristiwa lainnya ›': '更多事件 ›',
    'Belum ada agenda.': '暂无日程。', Tinggi: '高', Sedang: '中', Rendah: '低',
    Hubungi: '联系', Telepon: '拨打电话', 'Tautan belum tersedia': '链接不可用',
    'Ketik nama bank tujuan': '输入收款银行', 'Nomor rekening tujuan': '收款账号',
    'File harus berupa gambar.': '文件必须是图片。', 'Ukuran gambar maksimal 10 MB.': '图片大小不能超过 10 MB。',
    'Gambar tidak dapat dibaca.': '无法读取图片。', 'Pratinjau bukti transfer': '转账凭证预览',
    'Unggah bukti transfer': '上传转账凭证', 'Ganti / hapus gambar': '更换 / 删除图片',
    'Pilih pasar dan lakukan trading pertama Anda.': '选择一个市场以开始使用。',
    'Layanan mitra belum terhubung.': '合作伙伴服务尚未连接。',
    'Navigasi utama': '主导航', Informasi: '信息', Notifikasi: '通知',
    'Belum ada notifikasi.': '暂无通知。', Bantuan: '帮助',
    'Pusat Bantuan': '帮助中心', 'Untuk pertanyaan umum, buka menu FAQ. Layanan bantuan pelanggan belum terhubung.': '常见问题请查看 FAQ。客户服务尚未连接。',
    FAQ: '常见问题',
  },
};

const extendedTranslations: Record<Language, Record<string, string>> = {
  id: {},
  en: {
    'Promo HSB': 'HSB promotions', 'Bonus Hingga': 'Bonus up to', 'Pilih banner': 'Choose a banner',
    'Putar banner otomatis': 'Play banners automatically', 'Jeda banner otomatis': 'Pause banners',
    'Sinyal Trading': 'Trading Signals', 'Trading menjadi lebih mudah dengan analisa profesional': 'Trading made easier with professional analysis',
    'Lihat Semua': 'View all', 'Jual Signal': 'Sell Signal', 'Beli Signal': 'Buy Signal',
    'Estimasi Keuntungan': 'Estimated profit', 'Jika membuka 0.01 lot | Profit': 'For a 0.01 lot | Profit',
    'Selengkapnya': 'More details', 'Data contoh · Bukan rekomendasi investasi': 'Sample data · Not investment advice',
    'INFO PASAR': 'MARKET INFO', 'Data simulasi · Bukan harga pasar langsung': 'Simulated data · Not live market prices',
    'Berita Ekonomi': 'Economic News', 'Tetap up-to-date dengan berita terbaru': 'Stay up to date with the latest news',
    'Harga simulasi ': 'Simulated price ', 'Data ini bukan harga pasar langsung.': 'This is not a live market price.',
    'Sinyal XAUUSD dan USDJPY merupakan data contoh, bukan rekomendasi transaksi.': 'XAUUSD and USDJPY signals are sample data, not trade recommendations.',
    'Copy Signal': 'Copy Signal', 'Tersalin': 'Copied', 'Kembali ke pasar': 'Back to markets',
    'Ringkasan akun demo': 'Demo account summary', Demo: 'Demo', Ekuitas: 'Equity', Profit: 'Profit',
    'Cari Produk': 'Search Products', 'Pencarian Cepat': 'Quick Search', Arrangement: 'Arrangement',
    Favorit: 'Favorites', Simbol: 'Symbol', 'Ask Price': 'Ask Price', 'Bid Price': 'Bid Price',
    Spread: 'Spread', Chg: 'Change', 'Produk tidak ditemukan': 'No products found', 'Belum ada produk': 'No products yet',
    'Load more': 'Load more', 'Detail produk': 'Product details', Grafik: 'Chart', Berita: 'News',
    Signals: 'Signals', Posisi: 'Positions', Pesanan: 'Orders', Spesifikasi: 'Specifications',
    Open: 'Open', High: 'High', Close: 'Close', Low: 'Low', Indicators: 'Indicators',
    'Tampilkan candlestick': 'Show candlesticks', 'Tampilkan garis': 'Show line chart',
    'Perbesar grafik': 'Expand chart', 'Kecilkan grafik': 'Collapse chart',
    Produk: 'Product', Kelompok: 'Group', 'Mata uang': 'Currency', 'Ukuran minimum': 'Minimum size',
    'Jenis akun': 'Account type',
    'Filter Produk': 'Product Filter', 'Status Signal': 'Signal Status', Aktif: 'Active',
    Kedaluwarsa: 'Expired', 'Tidak ada sinyal.': 'No signals.',
    'Tidak ada agenda. Tambahkan agenda di atas.': 'No events yet. Add one above.',
    'Kembali': 'Back', 'Klaim': 'Claim', 'Berakhir 31 Okt 2026': 'Ends 31 Oct 2026',
    'Info Pasar Simulasi': 'Simulated market information', 'Menu cepat': 'Quick menu',
    'Ilustrasi pergerakan harga': 'Illustration of price movement', 'Bukan rekomendasi investasi.': 'Not investment advice.',
    'Bukan rekomendasi investasi': 'Not investment advice', Saldo: 'Balance', Margin: 'Margin',
    'Margin Bebas': 'Free Margin', 'lagi': 'more', 'Kategori pasar': 'Market categories',
    Hapus: 'Remove', Tambah: 'Add', 'Symbol Group': 'Symbol Group', Order: 'Order',
    Naikkan: 'Move up', Turunkan: 'Move down', 'Atur urutan': 'Reorder',
    'Take Profit': 'Take Profit', 'Stop Loss': 'Stop Loss',
    'Sinyal simulasi · Bukan rekomendasi investasi': 'Simulated signal · Not investment advice',
    'Trading tidak tersedia di pratinjau demo': 'Trading is unavailable in the demo preview',
    JUAL: 'SELL', BELI: 'BUY', Jual: 'Sell', Beli: 'Buy',
    'Pasar menerima lebih banyak wawasan dari informasi terbaru': 'Get more market insights from the latest information',
    'Daily Report HSB': 'HSB Daily Report', 'Pengenalan HSB': 'Introducing HSB',
    Klien: 'Clients', 'Daftar Klien': 'Client List', Ringkasan: 'Summary',
    'Pusat Sumber Daya Pemasaran': 'Marketing Resource Center', 'Alat Pemasaran': 'Marketing Tools',
    'Kode & Link Referral': 'Referral Code & Link', 'Hadiah Untuk Anda & Teman': 'Rewards for You and Friends',
    'Hadiah Saya': 'My Rewards', 'Teman yang Anda Ajak': 'Your Referrals',
    'AJAK TEMAN SEKARANG': 'INVITE FRIENDS NOW', 'Tarik Hadiah': 'Withdraw Rewards',
    'Materi Promosi': 'Promotional Materials', 'Pilih Grup Klien untuk Klien yang Anda Referensikan': 'Choose a client group for referred clients',
    'Penyaring': 'Filter', 'Unduh': 'Download', 'Tidak ada hasil': 'No results',
    'Daftar klien': 'Client list', 'Cari nama atau ID klien': 'Search client name or ID',
    'Trading menjadi lebih mudah dengan meniru analisa dari analis profesional dan terpercaya dari organisasi trading central.': 'Follow analysis from professional analysts and Trading Central.',
    'Pilih sinyal, tekan Copy Signal, lalu buka posisi dengan Open, TP, dan SL yang sama.': 'Choose a signal, select Copy Signal, then open a position using the same Open, TP, and SL.',
    'Pelajari bagaimana untuk menggunakan Copy Signal?': 'Learn how to use Copy Signal?',
    'Intraday': 'Intraday',
    'Navigasi mitra': 'Partner navigation', 'Anda dapatkan per teman': 'You earn per referral',
    'Teman Anda dapatkan': 'Your friend receives', deposit: 'deposit', bonus: 'bonus',
    'Kode Referral': 'Referral Code', 'Link Referral': 'Referral Link', Salin: 'Copy',
    'Bonus Level': 'Bonus Tiers', 'Semua hasil': 'All results', hasil: 'results',
    Filter: 'Filter', 'Cari klien': 'Search clients', 'Status klien': 'Client status',
    Semua: 'All', Lead: 'Lead', 'Sudah deposit': 'Deposited', 'Trader aktif': 'Active trader',
    'Total Klien': 'Total Clients', 'Lead Baru': 'New Leads', 'Deposit Pertama': 'First Deposit',
    'Trader Aktif': 'Active Traders', Banner: 'Banner', Video: 'Video',
    'Halaman Arahan': 'Landing Page', 'Bahasa materi': 'Content language',
    'Kembali ke welcome': 'Back to welcome', 'Buka Akun': 'Open an Account', Masuk: 'Sign in',
    'Metode masuk': 'Sign-in method', 'Nomor Telepon': 'Phone Number', 'Kata Sandi': 'Password',
    'Sembunyikan kata sandi': 'Hide password', 'Tampilkan kata sandi': 'Show password',
    'Kode Undangan (Opsional)': 'Invitation Code (Optional)', 'Kode Undangan': 'Invitation Code',
    'Masukkan kode undangan': 'Enter invitation code', 'Saya telah membaca dan menyetujui': 'I have read and agree to the',
    'Kebijakan Privasi': 'Privacy Policy', 'Lupa Kata Sandi': 'Forgot Password',
    Daftar: 'Register', 'Sudah punya akun?': 'Already have an account?', 'Belum punya akun?': 'Do not have an account?',
    'Masuk Sekarang': 'Sign in now', 'Daftar di Sini': 'Register here', 'Lihat Beranda': 'View Home',
    'Pendaftaran belum terhubung ke layanan akun.': 'Registration is not connected to an account service.',
    'Login belum terhubung ke layanan akun.': 'Login is not connected to an account service.',
    'Email atau kata sandi akun demo tidak valid.': 'The demo account email or password is invalid.',
    'Memiliki 12 hingga 128 karakter': 'Use 12 to 128 characters',
    'Memiliki setidaknya 1 angka': 'Include at least one number',
    'Memiliki setidaknya 1 huruf BESAR': 'Include at least one uppercase letter',
    'Memiliki setidaknya 1 huruf kecil': 'Include at least one lowercase letter',
    'Memiliki setidaknya 1 karakter khusus (@#$%...)': 'Include at least one special character (@#$%...)',
    'Tidak mengandung spasi': 'Do not use spaces',
    'Akun Demo': 'Demo Account', 'Pratinjau lokal': 'Local preview',
    'Akun simulasi untuk mencoba tampilan pengguna dan admin. Bukan untuk transaksi nyata.': 'Sample accounts for previewing the user and admin interfaces. Not for real transactions.',
    'Dokumen kebijakan privasi resmi belum ditambahkan.': 'The official privacy policy has not been added.',
    'Pemulihan kata sandi belum terhubung ke layanan akun.': 'Password recovery is not connected to an account service.',
    Trade: 'Trade', 'Copy Signals': 'Copy Signals', 'Daily Report': 'Daily Report',
    'Premium Program': 'Premium Program', 'Smart Trader': 'Smart Trader',
    'Hello Demo': 'Hello, Demo User', 'Salin UID': 'Copy UID', Dokumen: 'Documents',
    'Berita simulasi · Bukan rekomendasi investasi': 'Sample news · Not investment advice',
  },
  zh: {
    'Promo HSB': 'HSB 优惠', 'Bonus Hingga': '奖金高达', 'Pilih banner': '选择横幅',
    'Putar banner otomatis': '自动播放横幅', 'Jeda banner otomatis': '暂停横幅',
    'Sinyal Trading': '交易信号', 'Trading menjadi lebih mudah dengan analisa profesional': '专业分析，让交易更轻松',
    'Lihat Semua': '查看全部', 'Jual Signal': '卖出信号', 'Beli Signal': '买入信号',
    'Estimasi Keuntungan': '预估收益', 'Jika membuka 0.01 lot | Profit': '开仓 0.01 手 | 盈利',
    'Selengkapnya': '更多详情', 'Data contoh · Bukan rekomendasi investasi': '示例数据 · 非投资建议',
    'INFO PASAR': '市场资讯', 'Data simulasi · Bukan harga pasar langsung': '模拟数据 · 非实时市场价格',
    'Berita Ekonomi': '财经新闻', 'Tetap up-to-date dengan berita terbaru': '及时了解最新消息',
    'Harga simulasi ': '模拟价格 ', 'Data ini bukan harga pasar langsung.': '这不是实时市场价格。',
    'Sinyal XAUUSD dan USDJPY merupakan data contoh, bukan rekomendasi transaksi.': 'XAUUSD 和 USDJPY 信号为示例数据，不构成交易建议。',
    'Tersalin': '已复制', 'Kembali ke pasar': '返回市场',
    'Ringkasan akun demo': '模拟账户摘要', Demo: '模拟', Ekuitas: '净值', Profit: '利润',
    'Cari Produk': '搜索产品', 'Pencarian Cepat': '快速搜索', Arrangement: '排序',
    Favorit: '收藏', Simbol: '代码', 'Ask Price': '卖出价', 'Bid Price': '买入价',
    Spread: '点差', Chg: '涨跌', 'Produk tidak ditemukan': '未找到产品', 'Belum ada produk': '暂无产品',
    'Load more': '加载更多', Grafik: '图表', Berita: '新闻', Signals: '信号',
    Posisi: '持仓', Pesanan: '订单', Spesifikasi: '规格', Open: '开盘', High: '最高',
    Close: '收盘', Low: '最低', Indicators: '指标', 'Tampilkan candlestick': '显示蜡烛图',
    'Tampilkan garis': '显示折线图', 'Perbesar grafik': '放大图表', 'Kecilkan grafik': '缩小图表',
    Produk: '产品', Kelompok: '分组', 'Mata uang': '货币', 'Ukuran minimum': '最小交易量',
    'Jenis akun': '账户类型', 'Filter Produk': '产品筛选', 'Status Signal': '信号状态',
    Aktif: '进行中', Kedaluwarsa: '已过期', 'Tidak ada sinyal.': '暂无信号。',
    'Tidak ada agenda. Tambahkan agenda di atas.': '暂无日程，请在上方添加。',
    'Kembali': '返回', 'Klaim': '领取', 'Info Pasar Simulasi': '模拟市场信息',
    'Menu cepat': '快捷菜单', 'Ilustrasi pergerakan harga': '价格走势示意图',
    'Bukan rekomendasi investasi.': '非投资建议。', 'Bukan rekomendasi investasi': '非投资建议',
    Saldo: '余额', Margin: '保证金', 'Margin Bebas': '可用保证金', 'lagi': '更多',
    'Kategori pasar': '市场分类', Hapus: '移除', Tambah: '添加',
    'Symbol Group': '交易品种组', Order: '顺序', Naikkan: '上移', Turunkan: '下移',
    'Atur urutan': '调整顺序', 'Take Profit': '止盈', 'Stop Loss': '止损',
    'Sinyal simulasi · Bukan rekomendasi investasi': '模拟信号 · 非投资建议',
    'Trading tidak tersedia di pratinjau demo': '模拟预览中无法交易',
    JUAL: '卖出', BELI: '买入', Jual: '卖出', Beli: '买入',
    'Daily Report HSB': 'HSB 每日市场报告', 'Pengenalan HSB': 'HSB 介绍',
    Klien: '客户', 'Daftar Klien': '客户列表', Ringkasan: '摘要',
    'Pusat Sumber Daya Pemasaran': '营销资源中心', 'Alat Pemasaran': '营销工具',
    'Kode & Link Referral': '推荐码和链接', 'Hadiah Untuk Anda & Teman': '您和朋友的奖励',
    'Hadiah Saya': '我的奖励', 'Teman yang Anda Ajak': '邀请的朋友',
    'AJAK TEMAN SEKARANG': '立即邀请朋友', 'Tarik Hadiah': '提取奖励',
    'Materi Promosi': '推广素材', 'Pilih Grup Klien untuk Klien yang Anda Referensikan': '选择推荐客户的客户组',
    'Penyaring': '筛选', 'Unduh': '下载', 'Tidak ada hasil': '没有结果',
    'Cari nama atau ID klien': '搜索客户姓名或 ID', 'Intraday': '日内',
    'Berita simulasi · Bukan rekomendasi investasi': '示例新闻 · 非投资建议',
    'Navigasi mitra': '合作伙伴导航', 'Anda dapatkan per teman': '每位好友可获得',
    'Teman Anda dapatkan': '好友可获得', deposit: '存款', bonus: '奖金',
    'Kode Referral': '推荐码', 'Link Referral': '推荐链接', Salin: '复制',
    'Bonus Level': '奖励等级', 'Semua hasil': '全部结果', hasil: '个结果',
    Filter: '筛选', 'Cari klien': '搜索客户', 'Status klien': '客户状态',
    Semua: '全部', Lead: '潜在客户', 'Sudah deposit': '已存款', 'Trader aktif': '活跃交易者',
    'Total Klien': '客户总数', 'Lead Baru': '新潜在客户', 'Deposit Pertama': '首次存款',
    'Trader Aktif': '活跃交易者', Banner: '横幅', Video: '视频',
    'Halaman Arahan': '落地页', 'Bahasa materi': '素材语言',
    'Kembali ke welcome': '返回欢迎页', 'Buka Akun': '开户注册', Masuk: '登录',
    'Metode masuk': '登录方式', 'Nomor Telepon': '电话号码', 'Kata Sandi': '密码',
    'Sembunyikan kata sandi': '隐藏密码', 'Tampilkan kata sandi': '显示密码',
    'Kode Undangan (Opsional)': '邀请码（选填）', 'Kode Undangan': '邀请码',
    'Masukkan kode undangan': '输入邀请码', 'Saya telah membaca dan menyetujui': '我已阅读并同意',
    'Kebijakan Privasi': '隐私政策', 'Lupa Kata Sandi': '忘记密码',
    Daftar: '注册', 'Sudah punya akun?': '已有账户？', 'Belum punya akun?': '还没有账户？',
    'Masuk Sekarang': '立即登录', 'Daftar di Sini': '在此注册', 'Lihat Beranda': '查看首页',
    'Pendaftaran belum terhubung ke layanan akun.': '注册尚未连接到账户服务。',
    'Login belum terhubung ke layanan akun.': '登录尚未连接到账户服务。',
    'Email atau kata sandi akun demo tidak valid.': '演示账户的邮箱或密码无效。',
    'Memiliki 12 hingga 128 karakter': '使用 12 至 128 个字符',
    'Memiliki setidaknya 1 angka': '至少包含一个数字',
    'Memiliki setidaknya 1 huruf BESAR': '至少包含一个大写字母',
    'Memiliki setidaknya 1 huruf kecil': '至少包含一个小写字母',
    'Memiliki setidaknya 1 karakter khusus (@#$%...)': '至少包含一个特殊字符（@#$%...）',
    'Tidak mengandung spasi': '不能包含空格',
    'Akun Demo': '演示账户', 'Pratinjau lokal': '本地预览',
    'Akun simulasi untuk mencoba tampilan pengguna dan admin. Bukan untuk transaksi nyata.': '用于预览用户和管理员界面的示例账户，不可用于真实交易。',
    'Dokumen kebijakan privasi resmi belum ditambahkan.': '尚未添加正式隐私政策。',
    'Pemulihan kata sandi belum terhubung ke layanan akun.': '密码找回尚未连接到账户服务。',
    Trade: '交易', 'Copy Signals': '跟单信号', 'Daily Report': '每日报告',
    'Premium Program': '高级计划', 'Smart Trader': '智能交易',
    'Hello Demo': '演示用户，您好', 'Salin UID': '复制 UID', Dokumen: '文件',
    Email: '邮箱',
  },
};

type Preferences = {
  language: Language;
  setLanguage: (language: Language) => void;
  theme: Theme;
  toggleTheme: () => void;
};
const PreferencesContext = createContext<Preferences | null>(null);

export function AppPreferencesProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('id');
  const [theme, setThemeState] = useState<Theme>('light');
  const [loaded, setLoaded] = useState(false);
  useEffect(() => {
    try {
      const savedLanguage = localStorage.getItem('hsb-language');
      const savedTheme = localStorage.getItem('hsb-theme');
      if (savedLanguage === 'id' || savedLanguage === 'en' || savedLanguage === 'zh') setLanguageState(savedLanguage);
      if (savedTheme === 'dark' || savedTheme === 'light') setThemeState(savedTheme);
    } catch { /* use defaults when browser storage is unavailable */ }
    setLoaded(true);
  }, []);
  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.classList.toggle('dark', theme === 'dark');
    document.documentElement.style.colorScheme = theme;
    if (loaded) {
      try {
        localStorage.setItem('hsb-language', language);
        localStorage.setItem('hsb-theme', theme);
      } catch { /* keep this session usable without persistent storage */ }
    }
  }, [language, theme, loaded]);
  const setLanguage = (next: Language) => setLanguageState(next);
  const toggleTheme = () => setThemeState((current) => current === 'dark' ? 'light' : 'dark');
  return <PreferencesContext.Provider value={{ language, setLanguage, theme, toggleTheme }}>{children}</PreferencesContext.Provider>;
}

export function useAppPreferences() {
  const context = useContext(PreferencesContext);
  if (!context) throw new Error('AppPreferencesProvider missing');
  return context;
}

export function translate(text: string, language: Language) {
  return extendedTranslations[language][text] ?? translations[language][text] ?? text;
}
