import { useState } from 'react';
import { Link } from '@tanstack/react-router';
import { ArrowLeft, ArrowUp, ArrowDown, Search, SlidersHorizontal, Star, GripHorizontal, House, ChartNoAxesColumn, BriefcaseBusiness, Users, UserRound, ChevronsUp, X, Maximize2, CandlestickChart, LineChart, ChevronDown } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { bidPrice, type Product } from '@/lib/market-data';
import { useMarket } from '@/components/market-context';
import { SimulatedChart } from '@/components/simulated-chart';
import { useAppPreferences, translate } from '@/components/app-preferences';

export function MarketHeader({title,back=true,children}:{title:string;back?:boolean;children?:React.ReactNode}){const {language}=useAppPreferences();const tr=(text:string)=>translate(text,language);return <header className="market-header">{back&&<Button asChild variant="ghost" size="icon"><Link to="/pasar" aria-label={tr('Kembali ke pasar')}><ArrowLeft/></Link></Button>}<h1>{tr(title)}</h1><div className="market-header-actions">{children}</div></header>;}
export function DemoStrip(){const [expanded,setExpanded]=useState(false);const {language}=useAppPreferences();const tr=(text:string)=>translate(text,language);return <><div className="market-demo-strip"><Button variant="ghost" size="icon" aria-label={tr('Ringkasan akun demo')} aria-expanded={expanded} onClick={()=>setExpanded(!expanded)}><ChevronsUp/></Button><b>{tr('Demo')}</b><span>#90260762</span><div><small>{tr('Ekuitas')}</small><strong>10,000.00</strong></div><div><small>{tr('Profit')}</small><strong className="market-up">0.00</strong></div></div>{expanded&&<div className="market-demo-expanded"><span>{tr('Saldo')} <b>10,000.00 USD</b></span><span>{tr('Margin')} <b>0.00 USD</b></span><span>{tr('Margin Bebas')} <b>10,000.00 USD</b></span></div>}</>;}
function MarketNav(){const [notice,setNotice]=useState('');const {language}=useAppPreferences();const tr=(text:string)=>translate(text,language);return <><nav className="home-bottom-nav" aria-label={tr('Navigasi utama')}><Button asChild variant="ghost"><Link to="/beranda"><House/><span>{tr('Beranda')}</span></Link></Button><Button asChild variant="ghost"><Link to="/pasar" aria-current="page"><ChartNoAxesColumn/><span>{tr('Pasar')}</span></Link></Button><Button asChild variant="ghost"><Link to="/posisi"><BriefcaseBusiness/><span>{tr('Posisi')}</span></Link></Button><Button variant="ghost" onClick={()=>setNotice(tr('Layanan mitra belum terhubung.'))}><Users/><span>{tr('Mitra')}</span></Button><Button asChild variant="ghost"><Link to="/profil"><UserRound/><span>{tr('Profil')}</span></Link></Button></nav>{notice&&<div className="account-dialog-backdrop"><section className="account-dialog" role="dialog" aria-modal="true" aria-label={tr('Informasi')}><p>{notice}</p><Button onClick={()=>setNotice('')}>{tr('Tutup')}</Button></section></div>}</>;}
function ProductTable({items}:{items:Product[]}){const {favorites,toggleFavorite,products}=useMarket();const {language}=useAppPreferences();const tr=(text:string)=>translate(text,language);const [sort,setSort]=useState<'symbol'|'change'>('symbol');const [descending,setDescending]=useState(false);const order=(key:'symbol'|'change')=>{setDescending(sort===key?!descending:false);setSort(key);};const sorted=[...items].sort((a,b)=>(sort==='symbol'?a.symbol.localeCompare(b.symbol):a.change-b.change)*(descending?-1:1));return <div className="market-table"><div className="market-table-head"><Button variant="ghost" onClick={()=>order('symbol')}>↕ {tr('Simbol')}</Button><span>{tr('Ask Price')}<br/>{tr('Bid Price')}</span><span>{tr('Spread')}</span><Button variant="ghost" onClick={()=>order('change')}>↕ {tr('Chg')}</Button></div>{sorted.map(p=><div className="market-row" key={p.symbol}><Button variant="ghost" size="icon" className={`market-star ${favorites.includes(p.symbol)?'is-favorite':''}`} aria-label={`${favorites.includes(p.symbol)?tr('Hapus'):tr('Tambah')} ${tr('Favorit')} ${p.symbol}`} aria-pressed={favorites.includes(p.symbol)} onClick={()=>toggleFavorite(p.symbol)}><Star/></Button><Link to="/pasar/$symbol" params={{symbol:p.symbol}} className="market-product-link"><b>{p.symbol}</b><span className="market-quotes"><span className="market-up">{p.ask.toFixed(p.decimals)}</span><span className="market-down">{bidPrice(p).toFixed(p.decimals)}</span></span><span className="market-spread">{p.spread}</span><span className={`market-change ${p.change>=0?'positive':'negative'}`}>{p.change>=0?'+':''}{p.change.toFixed(2)}%</span></Link></div>)}{!sorted.length&&<div className="market-empty">{tr(items===products?'Produk tidak ditemukan':'Belum ada produk')}<small>—</small></div>}</div>;}
export function MarketScreen(){const {favorites,groups,products}=useMarket();const {language}=useAppPreferences();const tr=(text:string)=>translate(text,language);const [group,setGroupState]=useState(groups.includes('Forex')?'Forex':(groups[0]??'Favorit'));const [visible,setVisible]=useState(8);const setGroup=(g:string)=>{setGroupState(g);setVisible(8);};const list=products.filter(p=>group==='Favorit'?favorites.includes(p.symbol):p.group===group);return <main className="market-page"><div className="market-shell market-list-shell"><MarketHeader title="Pasar" back={false}><Button asChild variant="ghost" size="icon"><Link to="/cari-produk" aria-label={tr('Cari Produk')}><Search/></Link></Button><Button asChild variant="ghost" size="icon"><Link to="/arrangement" aria-label={tr('Arrangement')}><SlidersHorizontal/></Link></Button></MarketHeader><div className="market-tabs" role="tablist" aria-label={tr('Kategori pasar')}>{['Favorit',...groups].map(g=><Button variant="ghost" role="tab" aria-selected={g===group} key={g} onClick={()=>setGroup(g)}>{tr(g)}</Button>)}</div><ProductTable items={list.slice(0,visible)}/>{list.length>visible&&<div className="flex justify-center p-3"><Button variant="outline" onClick={()=>setVisible(v=>v+8)}>{tr('Load more')} ({list.length-visible} {tr('lagi')})</Button></div>}<footer className="market-fixed-account"><DemoStrip/></footer><MarketNav/></div></main>;}
export function SearchScreen(){const {products}=useMarket();const {language}=useAppPreferences();const tr=(text:string)=>translate(text,language);const [query,setQuery]=useState('');const filtered=products.filter(p=>`${p.symbol} ${p.name} ${p.group}`.toLowerCase().includes(query.toLowerCase().trim()));return <main className="market-page"><div className="market-shell"><MarketHeader title="Cari Produk"/><div className="market-search"><Search/><Input aria-label={tr('Pencarian Cepat')} placeholder={tr('Pencarian Cepat')} value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<Button variant="ghost" size="icon" aria-label={tr('Hapus pencarian')} onClick={()=>setQuery('')}><X/></Button>}</div>{filtered.length?<ProductTable items={filtered}/>:<p className="market-empty">{tr('Produk tidak ditemukan')}</p>}</div></main>;}
export function ArrangementScreen(){const {groups,moveGroup}=useMarket();const {language}=useAppPreferences();const tr=(text:string)=>translate(text,language);const [dragged,setDragged]=useState<number|null>(null);const [selected,setSelected]=useState<string|null>(null);return <main className="market-page"><div className="market-shell"><MarketHeader title="Arrangement"/><div className="market-arrangement-head"><span>{tr('Symbol Group')}</span><span>{tr('Order')}</span></div><div className="market-group-row">{tr('Favorit')}</div>{groups.map((group,index)=><div key={group} className={`market-group-row ${dragged===index?'is-dragging':''}`} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(dragged!==null)moveGroup(dragged,index);setDragged(null);}}><span>{tr(group)}</span><div>{selected===group&&<><Button variant="ghost" size="icon" disabled={index===0} aria-label={`${tr('Naikkan')} ${tr(group)}`} onClick={()=>moveGroup(index,index-1)}><ArrowUp/></Button><Button variant="ghost" size="icon" disabled={index===groups.length-1} aria-label={`${tr('Turunkan')} ${tr(group)}`} onClick={()=>moveGroup(index,index+1)}><ArrowDown/></Button></>}<Button variant="ghost" size="icon" draggable onDragStart={()=>setDragged(index)} onDragEnd={()=>setDragged(null)} onClick={()=>setSelected(selected===group?null:group)} aria-expanded={selected===group} aria-label={`${tr('Atur urutan')} ${tr(group)}`} title={`${tr('Atur urutan')} ${tr(group)}`}><GripHorizontal/></Button></div></div>)}</div></main>;}
export function MarketDetailScreen({ product }: { product: Product }) {
  const { favorites, toggleFavorite } = useMarket();
  const { language } = useAppPreferences();
  const tr = (text: string) => translate(text, language);
  const [tab, setTab] = useState('Grafik');
  const [interval, setInterval] = useState('1m');
  const [line, setLine] = useState(false);
  const [indicator, setIndicator] = useState(false);
  const [expanded, setExpanded] = useState(false);
  const priceDetails: [string, number][] = [['Open', product.ask * 0.997], ['High', product.ask * 1.0005], ['Close', product.ask * 0.999], ['Low', product.ask * 0.996]];

  return <main className="market-page">
    <div className={`market-shell market-detail-shell ${expanded ? 'market-chart-expanded' : ''}`}>
      <MarketHeader title={product.symbol}>
        <Button variant="ghost" size="icon" className={`market-star ${favorites.includes(product.symbol) ? 'is-favorite' : ''}`} aria-label={`Favorit ${product.symbol}`} aria-pressed={favorites.includes(product.symbol)} onClick={() => toggleFavorite(product.symbol)}><Star /></Button>
      </MarketHeader>
      <div className="market-detail-tabs market-tabs" role="tablist" aria-label="Detail produk">
        {['Grafik', 'Berita', 'Signals', 'Posisi', 'Pesanan', 'Spesifikasi'].map((value) => <Button key={value} variant="ghost" role="tab" aria-selected={tab === value} onClick={() => setTab(value)}>{tr(value)}{['Posisi', 'Pesanan'].includes(value) && <small>0</small>}</Button>)}
      </div>
      {tab === 'Grafik' ? <>
        <section className="market-detail-prices">
          <strong>{(product.ask - 0.01 / 10 ** (product.decimals - 3)).toFixed(product.decimals)}</strong>
          <dl>{priceDetails.map(([label, value]) => <div key={label}><dt>{tr(label)}</dt><dd>{value.toFixed(product.decimals)}</dd></div>)}</dl>
        </section>
        <div className="market-chart-tools">
          <label><select aria-label="Interval grafik" value={interval} onChange={(e) => setInterval(e.target.value)}>{['1m', '5m', '15m', '1h', '1D'].map((value) => <option key={value}>{value}</option>)}</select><ChevronDown /></label>
          <Button variant="ghost" size="icon" aria-label={line ? 'Tampilkan candlestick' : 'Tampilkan garis'} onClick={() => setLine(!line)}>{line ? <LineChart /> : <CandlestickChart />}</Button>
          <Button variant="ghost" aria-pressed={indicator} onClick={() => setIndicator(!indicator)}>ƒx <span>{tr('Indicators')}</span></Button>
          <Button variant="ghost" size="icon" aria-label={expanded ? 'Kecilkan grafik' : 'Perbesar grafik'} onClick={() => setExpanded(!expanded)}><Maximize2 /></Button>
        </div>
        <div className="market-chart-label"><span>{product.symbol} · {interval}</span><small className="market-up">{product.ask.toFixed(product.decimals)} {product.change >= 0 ? '+' : ''}{product.change.toFixed(2)}% · Simulasi</small></div>
        <SimulatedChart product={product} interval={interval} line={line} indicator={indicator} />
      </> : <section className="market-detail-content">
        {tab === 'Spesifikasi' ? <dl>{[['Produk', product.name], ['Kelompok', product.group], ['Mata uang', 'USD'], ['Ukuran minimum', '0.01 lot'], ['Spread', `${product.spread}`], ['Jenis akun', 'Demo']].map(([key, value]) => <div key={String(key)}><dt>{tr(String(key))}</dt><dd>{tr(String(value))}</dd></div>)}</dl>
          : tab === 'Berita' ? <><h2>{product.symbol}: ringkasan pasar</h2><p>Pergerakan {product.name} dalam sesi perdagangan simulasi.</p><small>Berita simulasi · Bukan rekomendasi investasi</small></>
              : tab === 'Signals' ? <><h2>{tr(product.change >= 0 ? 'Beli' : 'Jual')} · {product.symbol}</h2><dl><div><dt>{tr('Open')}</dt><dd>{product.ask.toFixed(product.decimals)}</dd></div><div><dt>{tr('Take Profit')}</dt><dd>{(product.ask * 1.002).toFixed(product.decimals)}</dd></div><div><dt>{tr('Stop Loss')}</dt><dd>{(product.ask * 0.999).toFixed(product.decimals)}</dd></div></dl><small>{tr('Sinyal simulasi · Bukan rekomendasi investasi')}</small></>
              : <p className="market-empty">Belum ada {tab.toLowerCase()}</p>}
      </section>}
      <div className="market-detail-footer">
        <div className="market-trade-actions">
          <Button variant="marketSell" disabled title={tr('Trading tidak tersedia di pratinjau demo')}>{tr('JUAL')}<small>{bidPrice(product).toFixed(product.decimals)}</small></Button>
          <span>{(product.spread / 10 ** product.decimals).toFixed(product.decimals)}</span>
          <Button variant="marketBuy" disabled title={tr('Trading tidak tersedia di pratinjau demo')}>{tr('BELI')}<small>{product.ask.toFixed(product.decimals)}</small></Button>
        </div>
        <DemoStrip />
      </div>
    </div>
  </main>;
}