/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AlatPemasaranRouteImport } from './routes/alat-pemasaran'
import { Route as ArrangementRouteImport } from './routes/arrangement'
import { Route as BahasaRouteImport } from './routes/bahasa'
import { Route as BankPenarikanRouteImport } from './routes/bank-penarikan'
import { Route as BerandaRouteImport } from './routes/beranda'
import { Route as BeritaRouteImport } from './routes/berita'
import { Route as CariProdukRouteImport } from './routes/cari-produk'
import { Route as DailyReportRouteImport } from './routes/daily-report'
import { Route as DepositRouteImport } from './routes/deposit'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GantiKataSandiRouteImport } from './routes/ganti-kata-sandi'
import { Route as InformasiAkunRouteImport } from './routes/informasi-akun'
import { Route as KalenderEkonomiRouteImport } from './routes/kalender-ekonomi'
import { Route as KlienRouteImport } from './routes/klien'
import { Route as LayananPelangganRouteImport } from './routes/layanan-pelanggan'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MitraRouteImport } from './routes/mitra'
import { Route as PasarRouteImport } from './routes/pasar'
import { Route as PosisiRouteImport } from './routes/posisi'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as PromoRouteImport } from './routes/promo'
import { Route as ProteksiDanaRouteImport } from './routes/proteksi-dana'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RiwayatPembayaranRouteImport } from './routes/riwayat-pembayaran'
import { Route as SinyalTradingRouteImport } from './routes/sinyal-trading'
import { Route as SmartTraderRouteImport } from './routes/smart-trader'
import { Route as WithdrawRouteImport } from './routes/withdraw'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminBerandaRouteImport } from './routes/admin.beranda'
import { Route as AdminBeritaRouteImport } from './routes/admin.berita'
import { Route as AdminCompoundingRouteImport } from './routes/admin.compounding'
import { Route as AdminDepositRouteImport } from './routes/admin.deposit'
import { Route as AdminMitraRouteImport } from './routes/admin.mitra'
import { Route as AdminNotifikasiRouteImport } from './routes/admin.notifikasi'
import { Route as AdminPasarRouteImport } from './routes/admin.pasar'
import { Route as AdminRekeningRouteImport } from './routes/admin.rekening'
import { Route as AdminUserRouteImport } from './routes/admin.user'
import { Route as AdminWithdrawRouteImport } from './routes/admin.withdraw'
import { Route as BeritaIndexRouteImport } from './routes/berita.index'
import { Route as BeritaIdRouteImport } from './routes/berita.$id'
import { Route as PasarIndexRouteImport } from './routes/pasar.index'
import { Route as PasarSymbolRouteImport } from './routes/pasar.$symbol'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AlatPemasaranRoute = AlatPemasaranRouteImport.update({
  id: '/alat-pemasaran',
  path: '/alat-pemasaran',
  getParentRoute: () => rootRouteImport,
} as any)
const ArrangementRoute = ArrangementRouteImport.update({
  id: '/arrangement',
  path: '/arrangement',
  getParentRoute: () => rootRouteImport,
} as any)
const BahasaRoute = BahasaRouteImport.update({
  id: '/bahasa',
  path: '/bahasa',
  getParentRoute: () => rootRouteImport,
} as any)
const BankPenarikanRoute = BankPenarikanRouteImport.update({
  id: '/bank-penarikan',
  path: '/bank-penarikan',
  getParentRoute: () => rootRouteImport,
} as any)
const BerandaRoute = BerandaRouteImport.update({
  id: '/beranda',
  path: '/beranda',
  getParentRoute: () => rootRouteImport,
} as any)
const BeritaRoute = BeritaRouteImport.update({
  id: '/berita',
  path: '/berita',
  getParentRoute: () => rootRouteImport,
} as any)
const CariProdukRoute = CariProdukRouteImport.update({
  id: '/cari-produk',
  path: '/cari-produk',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyReportRoute = DailyReportRouteImport.update({
  id: '/daily-report',
  path: '/daily-report',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositRoute = DepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GantiKataSandiRoute = GantiKataSandiRouteImport.update({
  id: '/ganti-kata-sandi',
  path: '/ganti-kata-sandi',
  getParentRoute: () => rootRouteImport,
} as any)
const InformasiAkunRoute = InformasiAkunRouteImport.update({
  id: '/informasi-akun',
  path: '/informasi-akun',
  getParentRoute: () => rootRouteImport,
} as any)
const KalenderEkonomiRoute = KalenderEkonomiRouteImport.update({
  id: '/kalender-ekonomi',
  path: '/kalender-ekonomi',
  getParentRoute: () => rootRouteImport,
} as any)
const KlienRoute = KlienRouteImport.update({
  id: '/klien',
  path: '/klien',
  getParentRoute: () => rootRouteImport,
} as any)
const LayananPelangganRoute = LayananPelangganRouteImport.update({
  id: '/layanan-pelanggan',
  path: '/layanan-pelanggan',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MitraRoute = MitraRouteImport.update({
  id: '/mitra',
  path: '/mitra',
  getParentRoute: () => rootRouteImport,
} as any)
const PasarRoute = PasarRouteImport.update({
  id: '/pasar',
  path: '/pasar',
  getParentRoute: () => rootRouteImport,
} as any)
const PosisiRoute = PosisiRouteImport.update({
  id: '/posisi',
  path: '/posisi',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const PromoRoute = PromoRouteImport.update({
  id: '/promo',
  path: '/promo',
  getParentRoute: () => rootRouteImport,
} as any)
const ProteksiDanaRoute = ProteksiDanaRouteImport.update({
  id: '/proteksi-dana',
  path: '/proteksi-dana',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RiwayatPembayaranRoute = RiwayatPembayaranRouteImport.update({
  id: '/riwayat-pembayaran',
  path: '/riwayat-pembayaran',
  getParentRoute: () => rootRouteImport,
} as any)
const SinyalTradingRoute = SinyalTradingRouteImport.update({
  id: '/sinyal-trading',
  path: '/sinyal-trading',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartTraderRoute = SmartTraderRouteImport.update({
  id: '/smart-trader',
  path: '/smart-trader',
  getParentRoute: () => rootRouteImport,
} as any)
const WithdrawRoute = WithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBerandaRoute = AdminBerandaRouteImport.update({
  id: '/beranda',
  path: '/beranda',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBeritaRoute = AdminBeritaRouteImport.update({
  id: '/berita',
  path: '/berita',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCompoundingRoute = AdminCompoundingRouteImport.update({
  id: '/compounding',
  path: '/compounding',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDepositRoute = AdminDepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMitraRoute = AdminMitraRouteImport.update({
  id: '/mitra',
  path: '/mitra',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotifikasiRoute = AdminNotifikasiRouteImport.update({
  id: '/notifikasi',
  path: '/notifikasi',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPasarRoute = AdminPasarRouteImport.update({
  id: '/pasar',
  path: '/pasar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRekeningRoute = AdminRekeningRouteImport.update({
  id: '/rekening',
  path: '/rekening',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUserRoute = AdminUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWithdrawRoute = AdminWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => AdminRoute,
} as any)
const BeritaIndexRoute = BeritaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BeritaRoute,
} as any)
const BeritaIdRoute = BeritaIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BeritaRoute,
} as any)
const PasarIndexRoute = PasarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PasarRoute,
} as any)
const PasarSymbolRoute = PasarSymbolRouteImport.update({
  id: '/$symbol',
  path: '/$symbol',
  getParentRoute: () => PasarRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/alat-pemasaran': typeof AlatPemasaranRoute
  '/arrangement': typeof ArrangementRoute
  '/bahasa': typeof BahasaRoute
  '/bank-penarikan': typeof BankPenarikanRoute
  '/beranda': typeof BerandaRoute
  '/berita': typeof BeritaRouteWithChildren
  '/cari-produk': typeof CariProdukRoute
  '/daily-report': typeof DailyReportRoute
  '/deposit': typeof DepositRoute
  '/faq': typeof FaqRoute
  '/ganti-kata-sandi': typeof GantiKataSandiRoute
  '/informasi-akun': typeof InformasiAkunRoute
  '/kalender-ekonomi': typeof KalenderEkonomiRoute
  '/klien': typeof KlienRoute
  '/layanan-pelanggan': typeof LayananPelangganRoute
  '/login': typeof LoginRoute
  '/mitra': typeof MitraRoute
  '/pasar': typeof PasarRouteWithChildren
  '/posisi': typeof PosisiRoute
  '/profil': typeof ProfilRoute
  '/promo': typeof PromoRoute
  '/proteksi-dana': typeof ProteksiDanaRoute
  '/register': typeof RegisterRoute
  '/riwayat-pembayaran': typeof RiwayatPembayaranRoute
  '/sinyal-trading': typeof SinyalTradingRoute
  '/smart-trader': typeof SmartTraderRoute
  '/withdraw': typeof WithdrawRoute
  '/admin/beranda': typeof AdminBerandaRoute
  '/admin/berita': typeof AdminBeritaRoute
  '/admin/compounding': typeof AdminCompoundingRoute
  '/admin/deposit': typeof AdminDepositRoute
  '/admin/mitra': typeof AdminMitraRoute
  '/admin/notifikasi': typeof AdminNotifikasiRoute
  '/admin/pasar': typeof AdminPasarRoute
  '/admin/rekening': typeof AdminRekeningRoute
  '/admin/user': typeof AdminUserRoute
  '/admin/withdraw': typeof AdminWithdrawRoute
  '/berita/$id': typeof BeritaIdRoute
  '/pasar/$symbol': typeof PasarSymbolRoute
  '/admin/': typeof AdminIndexRoute
  '/berita/': typeof BeritaIndexRoute
  '/pasar/': typeof PasarIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alat-pemasaran': typeof AlatPemasaranRoute
  '/arrangement': typeof ArrangementRoute
  '/bahasa': typeof BahasaRoute
  '/bank-penarikan': typeof BankPenarikanRoute
  '/beranda': typeof BerandaRoute
  '/cari-produk': typeof CariProdukRoute
  '/daily-report': typeof DailyReportRoute
  '/deposit': typeof DepositRoute
  '/faq': typeof FaqRoute
  '/ganti-kata-sandi': typeof GantiKataSandiRoute
  '/informasi-akun': typeof InformasiAkunRoute
  '/kalender-ekonomi': typeof KalenderEkonomiRoute
  '/klien': typeof KlienRoute
  '/layanan-pelanggan': typeof LayananPelangganRoute
  '/login': typeof LoginRoute
  '/mitra': typeof MitraRoute
  '/posisi': typeof PosisiRoute
  '/profil': typeof ProfilRoute
  '/promo': typeof PromoRoute
  '/proteksi-dana': typeof ProteksiDanaRoute
  '/register': typeof RegisterRoute
  '/riwayat-pembayaran': typeof RiwayatPembayaranRoute
  '/sinyal-trading': typeof SinyalTradingRoute
  '/smart-trader': typeof SmartTraderRoute
  '/withdraw': typeof WithdrawRoute
  '/admin/beranda': typeof AdminBerandaRoute
  '/admin/berita': typeof AdminBeritaRoute
  '/admin/compounding': typeof AdminCompoundingRoute
  '/admin/deposit': typeof AdminDepositRoute
  '/admin/mitra': typeof AdminMitraRoute
  '/admin/notifikasi': typeof AdminNotifikasiRoute
  '/admin/pasar': typeof AdminPasarRoute
  '/admin/rekening': typeof AdminRekeningRoute
  '/admin/user': typeof AdminUserRoute
  '/admin/withdraw': typeof AdminWithdrawRoute
  '/berita/$id': typeof BeritaIdRoute
  '/pasar/$symbol': typeof PasarSymbolRoute
  '/admin': typeof AdminIndexRoute
  '/berita': typeof BeritaIndexRoute
  '/pasar': typeof PasarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/alat-pemasaran': typeof AlatPemasaranRoute
  '/arrangement': typeof ArrangementRoute
  '/bahasa': typeof BahasaRoute
  '/bank-penarikan': typeof BankPenarikanRoute
  '/beranda': typeof BerandaRoute
  '/berita': typeof BeritaRouteWithChildren
  '/cari-produk': typeof CariProdukRoute
  '/daily-report': typeof DailyReportRoute
  '/deposit': typeof DepositRoute
  '/faq': typeof FaqRoute
  '/ganti-kata-sandi': typeof GantiKataSandiRoute
  '/informasi-akun': typeof InformasiAkunRoute
  '/kalender-ekonomi': typeof KalenderEkonomiRoute
  '/klien': typeof KlienRoute
  '/layanan-pelanggan': typeof LayananPelangganRoute
  '/login': typeof LoginRoute
  '/mitra': typeof MitraRoute
  '/pasar': typeof PasarRouteWithChildren
  '/posisi': typeof PosisiRoute
  '/profil': typeof ProfilRoute
  '/promo': typeof PromoRoute
  '/proteksi-dana': typeof ProteksiDanaRoute
  '/register': typeof RegisterRoute
  '/riwayat-pembayaran': typeof RiwayatPembayaranRoute
  '/sinyal-trading': typeof SinyalTradingRoute
  '/smart-trader': typeof SmartTraderRoute
  '/withdraw': typeof WithdrawRoute
  '/admin/beranda': typeof AdminBerandaRoute
  '/admin/berita': typeof AdminBeritaRoute
  '/admin/compounding': typeof AdminCompoundingRoute
  '/admin/deposit': typeof AdminDepositRoute
  '/admin/mitra': typeof AdminMitraRoute
  '/admin/notifikasi': typeof AdminNotifikasiRoute
  '/admin/pasar': typeof AdminPasarRoute
  '/admin/rekening': typeof AdminRekeningRoute
  '/admin/user': typeof AdminUserRoute
  '/admin/withdraw': typeof AdminWithdrawRoute
  '/berita/$id': typeof BeritaIdRoute
  '/pasar/$symbol': typeof PasarSymbolRoute
  '/admin/': typeof AdminIndexRoute
  '/berita/': typeof BeritaIndexRoute
  '/pasar/': typeof PasarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/alat-pemasaran'
    | '/arrangement'
    | '/bahasa'
    | '/bank-penarikan'
    | '/beranda'
    | '/berita'
    | '/cari-produk'
    | '/daily-report'
    | '/deposit'
    | '/faq'
    | '/ganti-kata-sandi'
    | '/informasi-akun'
    | '/kalender-ekonomi'
    | '/klien'
    | '/layanan-pelanggan'
    | '/login'
    | '/mitra'
    | '/pasar'
    | '/posisi'
    | '/profil'
    | '/promo'
    | '/proteksi-dana'
    | '/register'
    | '/riwayat-pembayaran'
    | '/sinyal-trading'
    | '/smart-trader'
    | '/withdraw'
    | '/admin/beranda'
    | '/admin/berita'
    | '/admin/compounding'
    | '/admin/deposit'
    | '/admin/mitra'
    | '/admin/notifikasi'
    | '/admin/pasar'
    | '/admin/rekening'
    | '/admin/user'
    | '/admin/withdraw'
    | '/berita/$id'
    | '/pasar/$symbol'
    | '/admin/'
    | '/berita/'
    | '/pasar/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alat-pemasaran'
    | '/arrangement'
    | '/bahasa'
    | '/bank-penarikan'
    | '/beranda'
    | '/cari-produk'
    | '/daily-report'
    | '/deposit'
    | '/faq'
    | '/ganti-kata-sandi'
    | '/informasi-akun'
    | '/kalender-ekonomi'
    | '/klien'
    | '/layanan-pelanggan'
    | '/login'
    | '/mitra'
    | '/posisi'
    | '/profil'
    | '/promo'
    | '/proteksi-dana'
    | '/register'
    | '/riwayat-pembayaran'
    | '/sinyal-trading'
    | '/smart-trader'
    | '/withdraw'
    | '/admin/beranda'
    | '/admin/berita'
    | '/admin/compounding'
    | '/admin/deposit'
    | '/admin/mitra'
    | '/admin/notifikasi'
    | '/admin/pasar'
    | '/admin/rekening'
    | '/admin/user'
    | '/admin/withdraw'
    | '/berita/$id'
    | '/pasar/$symbol'
    | '/admin'
    | '/berita'
    | '/pasar'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/alat-pemasaran'
    | '/arrangement'
    | '/bahasa'
    | '/bank-penarikan'
    | '/beranda'
    | '/berita'
    | '/cari-produk'
    | '/daily-report'
    | '/deposit'
    | '/faq'
    | '/ganti-kata-sandi'
    | '/informasi-akun'
    | '/kalender-ekonomi'
    | '/klien'
    | '/layanan-pelanggan'
    | '/login'
    | '/mitra'
    | '/pasar'
    | '/posisi'
    | '/profil'
    | '/promo'
    | '/proteksi-dana'
    | '/register'
    | '/riwayat-pembayaran'
    | '/sinyal-trading'
    | '/smart-trader'
    | '/withdraw'
    | '/admin/beranda'
    | '/admin/berita'
    | '/admin/compounding'
    | '/admin/deposit'
    | '/admin/mitra'
    | '/admin/notifikasi'
    | '/admin/pasar'
    | '/admin/rekening'
    | '/admin/user'
    | '/admin/withdraw'
    | '/berita/$id'
    | '/pasar/$symbol'
    | '/admin/'
    | '/berita/'
    | '/pasar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AlatPemasaranRoute: typeof AlatPemasaranRoute
  ArrangementRoute: typeof ArrangementRoute
  BahasaRoute: typeof BahasaRoute
  BankPenarikanRoute: typeof BankPenarikanRoute
  BerandaRoute: typeof BerandaRoute
  BeritaRoute: typeof BeritaRouteWithChildren
  CariProdukRoute: typeof CariProdukRoute
  DailyReportRoute: typeof DailyReportRoute
  DepositRoute: typeof DepositRoute
  FaqRoute: typeof FaqRoute
  GantiKataSandiRoute: typeof GantiKataSandiRoute
  InformasiAkunRoute: typeof InformasiAkunRoute
  KalenderEkonomiRoute: typeof KalenderEkonomiRoute
  KlienRoute: typeof KlienRoute
  LayananPelangganRoute: typeof LayananPelangganRoute
  LoginRoute: typeof LoginRoute
  MitraRoute: typeof MitraRoute
  PasarRoute: typeof PasarRouteWithChildren
  PosisiRoute: typeof PosisiRoute
  ProfilRoute: typeof ProfilRoute
  PromoRoute: typeof PromoRoute
  ProteksiDanaRoute: typeof ProteksiDanaRoute
  RegisterRoute: typeof RegisterRoute
  RiwayatPembayaranRoute: typeof RiwayatPembayaranRoute
  SinyalTradingRoute: typeof SinyalTradingRoute
  SmartTraderRoute: typeof SmartTraderRoute
  WithdrawRoute: typeof WithdrawRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alat-pemasaran': {
      id: '/alat-pemasaran'
      path: '/alat-pemasaran'
      fullPath: '/alat-pemasaran'
      preLoaderRoute: typeof AlatPemasaranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arrangement': {
      id: '/arrangement'
      path: '/arrangement'
      fullPath: '/arrangement'
      preLoaderRoute: typeof ArrangementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bahasa': {
      id: '/bahasa'
      path: '/bahasa'
      fullPath: '/bahasa'
      preLoaderRoute: typeof BahasaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank-penarikan': {
      id: '/bank-penarikan'
      path: '/bank-penarikan'
      fullPath: '/bank-penarikan'
      preLoaderRoute: typeof BankPenarikanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beranda': {
      id: '/beranda'
      path: '/beranda'
      fullPath: '/beranda'
      preLoaderRoute: typeof BerandaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berita': {
      id: '/berita'
      path: '/berita'
      fullPath: '/berita'
      preLoaderRoute: typeof BeritaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cari-produk': {
      id: '/cari-produk'
      path: '/cari-produk'
      fullPath: '/cari-produk'
      preLoaderRoute: typeof CariProdukRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-report': {
      id: '/daily-report'
      path: '/daily-report'
      fullPath: '/daily-report'
      preLoaderRoute: typeof DailyReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposit': {
      id: '/deposit'
      path: '/deposit'
      fullPath: '/deposit'
      preLoaderRoute: typeof DepositRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ganti-kata-sandi': {
      id: '/ganti-kata-sandi'
      path: '/ganti-kata-sandi'
      fullPath: '/ganti-kata-sandi'
      preLoaderRoute: typeof GantiKataSandiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informasi-akun': {
      id: '/informasi-akun'
      path: '/informasi-akun'
      fullPath: '/informasi-akun'
      preLoaderRoute: typeof InformasiAkunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kalender-ekonomi': {
      id: '/kalender-ekonomi'
      path: '/kalender-ekonomi'
      fullPath: '/kalender-ekonomi'
      preLoaderRoute: typeof KalenderEkonomiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/klien': {
      id: '/klien'
      path: '/klien'
      fullPath: '/klien'
      preLoaderRoute: typeof KlienRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layanan-pelanggan': {
      id: '/layanan-pelanggan'
      path: '/layanan-pelanggan'
      fullPath: '/layanan-pelanggan'
      preLoaderRoute: typeof LayananPelangganRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mitra': {
      id: '/mitra'
      path: '/mitra'
      fullPath: '/mitra'
      preLoaderRoute: typeof MitraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pasar': {
      id: '/pasar'
      path: '/pasar'
      fullPath: '/pasar'
      preLoaderRoute: typeof PasarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posisi': {
      id: '/posisi'
      path: '/posisi'
      fullPath: '/posisi'
      preLoaderRoute: typeof PosisiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promo': {
      id: '/promo'
      path: '/promo'
      fullPath: '/promo'
      preLoaderRoute: typeof PromoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proteksi-dana': {
      id: '/proteksi-dana'
      path: '/proteksi-dana'
      fullPath: '/proteksi-dana'
      preLoaderRoute: typeof ProteksiDanaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/riwayat-pembayaran': {
      id: '/riwayat-pembayaran'
      path: '/riwayat-pembayaran'
      fullPath: '/riwayat-pembayaran'
      preLoaderRoute: typeof RiwayatPembayaranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sinyal-trading': {
      id: '/sinyal-trading'
      path: '/sinyal-trading'
      fullPath: '/sinyal-trading'
      preLoaderRoute: typeof SinyalTradingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-trader': {
      id: '/smart-trader'
      path: '/smart-trader'
      fullPath: '/smart-trader'
      preLoaderRoute: typeof SmartTraderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/withdraw': {
      id: '/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof WithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/beranda': {
      id: '/admin/beranda'
      path: '/beranda'
      fullPath: '/admin/beranda'
      preLoaderRoute: typeof AdminBerandaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/berita': {
      id: '/admin/berita'
      path: '/berita'
      fullPath: '/admin/berita'
      preLoaderRoute: typeof AdminBeritaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/compounding': {
      id: '/admin/compounding'
      path: '/compounding'
      fullPath: '/admin/compounding'
      preLoaderRoute: typeof AdminCompoundingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/deposit': {
      id: '/admin/deposit'
      path: '/deposit'
      fullPath: '/admin/deposit'
      preLoaderRoute: typeof AdminDepositRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mitra': {
      id: '/admin/mitra'
      path: '/mitra'
      fullPath: '/admin/mitra'
      preLoaderRoute: typeof AdminMitraRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifikasi': {
      id: '/admin/notifikasi'
      path: '/notifikasi'
      fullPath: '/admin/notifikasi'
      preLoaderRoute: typeof AdminNotifikasiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pasar': {
      id: '/admin/pasar'
      path: '/pasar'
      fullPath: '/admin/pasar'
      preLoaderRoute: typeof AdminPasarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rekening': {
      id: '/admin/rekening'
      path: '/rekening'
      fullPath: '/admin/rekening'
      preLoaderRoute: typeof AdminRekeningRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/user': {
      id: '/admin/user'
      path: '/user'
      fullPath: '/admin/user'
      preLoaderRoute: typeof AdminUserRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/withdraw': {
      id: '/admin/withdraw'
      path: '/withdraw'
      fullPath: '/admin/withdraw'
      preLoaderRoute: typeof AdminWithdrawRouteImport
      parentRoute: typeof AdminRoute
    }
    '/berita/': {
      id: '/berita/'
      path: '/'
      fullPath: '/berita/'
      preLoaderRoute: typeof BeritaIndexRouteImport
      parentRoute: typeof BeritaRoute
    }
    '/berita/$id': {
      id: '/berita/$id'
      path: '/$id'
      fullPath: '/berita/$id'
      preLoaderRoute: typeof BeritaIdRouteImport
      parentRoute: typeof BeritaRoute
    }
    '/pasar/': {
      id: '/pasar/'
      path: '/'
      fullPath: '/pasar/'
      preLoaderRoute: typeof PasarIndexRouteImport
      parentRoute: typeof PasarRoute
    }
    '/pasar/$symbol': {
      id: '/pasar/$symbol'
      path: '/$symbol'
      fullPath: '/pasar/$symbol'
      preLoaderRoute: typeof PasarSymbolRouteImport
      parentRoute: typeof PasarRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBerandaRoute: typeof AdminBerandaRoute
  AdminBeritaRoute: typeof AdminBeritaRoute
  AdminCompoundingRoute: typeof AdminCompoundingRoute
  AdminDepositRoute: typeof AdminDepositRoute
  AdminMitraRoute: typeof AdminMitraRoute
  AdminNotifikasiRoute: typeof AdminNotifikasiRoute
  AdminPasarRoute: typeof AdminPasarRoute
  AdminRekeningRoute: typeof AdminRekeningRoute
  AdminUserRoute: typeof AdminUserRoute
  AdminWithdrawRoute: typeof AdminWithdrawRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBerandaRoute: AdminBerandaRoute,
  AdminBeritaRoute: AdminBeritaRoute,
  AdminCompoundingRoute: AdminCompoundingRoute,
  AdminDepositRoute: AdminDepositRoute,
  AdminMitraRoute: AdminMitraRoute,
  AdminNotifikasiRoute: AdminNotifikasiRoute,
  AdminPasarRoute: AdminPasarRoute,
  AdminRekeningRoute: AdminRekeningRoute,
  AdminUserRoute: AdminUserRoute,
  AdminWithdrawRoute: AdminWithdrawRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BeritaRouteChildren {
  BeritaIdRoute: typeof BeritaIdRoute
  BeritaIndexRoute: typeof BeritaIndexRoute
}

const BeritaRouteChildren: BeritaRouteChildren = {
  BeritaIdRoute: BeritaIdRoute,
  BeritaIndexRoute: BeritaIndexRoute,
}

const BeritaRouteWithChildren =
  BeritaRoute._addFileChildren(BeritaRouteChildren)

interface PasarRouteChildren {
  PasarSymbolRoute: typeof PasarSymbolRoute
  PasarIndexRoute: typeof PasarIndexRoute
}

const PasarRouteChildren: PasarRouteChildren = {
  PasarSymbolRoute: PasarSymbolRoute,
  PasarIndexRoute: PasarIndexRoute,
}

const PasarRouteWithChildren = PasarRoute._addFileChildren(PasarRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AlatPemasaranRoute: AlatPemasaranRoute,
  ArrangementRoute: ArrangementRoute,
  BahasaRoute: BahasaRoute,
  BankPenarikanRoute: BankPenarikanRoute,
  BerandaRoute: BerandaRoute,
  BeritaRoute: BeritaRouteWithChildren,
  CariProdukRoute: CariProdukRoute,
  DailyReportRoute: DailyReportRoute,
  DepositRoute: DepositRoute,
  FaqRoute: FaqRoute,
  GantiKataSandiRoute: GantiKataSandiRoute,
  InformasiAkunRoute: InformasiAkunRoute,
  KalenderEkonomiRoute: KalenderEkonomiRoute,
  KlienRoute: KlienRoute,
  LayananPelangganRoute: LayananPelangganRoute,
  LoginRoute: LoginRoute,
  MitraRoute: MitraRoute,
  PasarRoute: PasarRouteWithChildren,
  PosisiRoute: PosisiRoute,
  ProfilRoute: ProfilRoute,
  PromoRoute: PromoRoute,
  ProteksiDanaRoute: ProteksiDanaRoute,
  RegisterRoute: RegisterRoute,
  RiwayatPembayaranRoute: RiwayatPembayaranRoute,
  SinyalTradingRoute: SinyalTradingRoute,
  SmartTraderRoute: SmartTraderRoute,
  WithdrawRoute: WithdrawRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
